# -*- coding: utf-8 -*-
"""coding problems

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFCUL1IAsTpQsm8oz99IQhpNLJU1MmTQ
"""

num=float(input("enetr"))
dir=num%4
if abs(dir)==0:
    print("south")
elif abs(dir)==1:
    print("east")
elif abs(dir)==2:
    print("west")
elif abs(dir)==3:
  print("north")
else:
  print("uhgiw")

num=float(input("enetr"))
dir=num%7
if abs(dir)==0:
    print("sunday")
elif abs(dir)==1:
    print("monday")
elif abs(dir)==2:
    print("tuesday")
elif abs(dir)==3:
    print("wednesday")
elif abs(dir)==4:
    print("thursday")
elif abs(dir)==5:
    print("friday")
elif abs(dir)==6:
    print("saturday")
else:
    print("fhgiu")

name=input("enter the string/n")
newname=name.lower()
num = 0
for i in range(len(newname)):
  if (name[i] in 'aeiou'):

    num=num+1

print(num)

cur=int(input("enetr the unit"))
if cur<=100:
    print(cur*3)
elif cur>100 and cur<=150:
    print(cur*4)
elif cur>150 and cur<=200:
    print(cur*5)
else:
    print(cur*10)

cur=int(input("enetr the unit"))
if cur<=100:
    t_cur=cur*3
    print(t_cur)
elif cur>100 and cur<=150:
    t_cur=(100*3)+((cur-100)*4)
    print(t_cur)
elif cur>150 and cur<=200:
    t_cur=(100*3)+(50*4)+((cur-150)*5)
    print(t_cur)
else:
    t_cur=(100*3)+(50*4)+(50*5)+((cur-200)*10)
    print(t_cur)

start=int(input("enter the start"))
size=int(input("enter the end"))

for i in range(1,size+1):

    print(start+i)
    sum=0
    for j in range(1,i+1):
        sum=sum+start+j


print("sum",sum)

size=int(input("enter the size"))
mul=1
for i in range(size):
    num=int(input("enter the number"))
    mul=mul*num
print("multiplication",mul)

string=input("enter:")
sm_name=string.lower()
rev_string=("")
for i in sm_name:
    rev_string=i+rev_string
print(rev_string )
if sm_name==rev_string:
    print("palindrome")
else:
    print("not palindrome")

n=int(input("enetr"))
count=0
for i in range(1,n+1):

  if n%i==0:

    count+=1
if count>2:
  print("true")
else:
  print("false")

6rows=int(input("enter the row"))
cols=int(input("enter the col"))
for i in range(rows,cols):
  if i%2==0:
    print("+ "*cols)
  else:
    print("- "*cols)

n=int(input("enter n:"))
m=int(input("enter m:"))

for i in range(1,n+2):
  for j in range(1,m+2):
    if i==1 or i==n+1 or j==1 or j==m+1:
      print("* ",end="")
    else:
      print("- ",end="")
  print()

n=int(input("enter n:"))
m=int(input("enter m:"))
for i in range(1,m+3):
  if i==1 or i==m+2:
    print("+"+"-"*((n+2)-2)+"+")
  else:
    print("|"+" "*((n+2)-2)+"|")

#prime number

n=int(input("enter"))
count=0
for i in range(2,n+1):
  if i%1==0 or i%i==0:
    count+=1
  if count==2:
      print(i)

n=int(input("enter"))
count=1
for i in range(2,n+1):
  if m%i==0:
    count+=1
if count==2:
      print("prime number")
else:
  print("not")

n=int(input(""))
for i in range(2,n+1):
  if n>1:
    factor=0
  else:
    factor=1
  for j in range(2,i):
    if i%j==0:
      factor+=1
  if factor==0:
    print(i)
  else:
    pass

list1=[1,30,2,9,6,4]
print(list1)
max=list1[0]
for i in list1:
    if i >max:
        max=i

print(max)

n=int(input("eneter"))
list1=[]

for i in range(n):
    list2=int(input())
    list1.append(list2)
print(list1)
max=list1[0]
for i in list1:
    if i >max:
        max=i


print(max)

list=list(map(int,input().split()))
print(list)
max=0
for i in list:
  if i<max :
    max=max
  else:
    max=i
print(max)



num=int(input())
if num%10==1:
  num1=1*100
  print(num)

num=int(input("enter:"))

rev_num=str(num)
emp_num=()
for i in rev_num:
      print(i)
      rev_num=i+rev_num
      emp_num=int(rev_num)
print(emp_num)


"""print(rev_num)
 if num==rev_num:
     print("palindrome")
 else:
     print("not palindrome")"""

num=int(input())
rev_num=0
while num>0:

  rev_num=(rev_num*10)+(num%10)
  num=num//10
print(rev_num)

num = int (input())
sum = 0
for i in range(1,num):
  if(num%i==0):
    sum+=i
if(sum==num):
  print("perfect number")
else:
  print("not a perfect number")

list1=[1,4,3,6,7]
max=0
for i in range(len(list1)):
    for j in range(i+1,len(list1)):
        if list1[i]*list1[j]>max:
            max=list1[i]*list1[j]
print(max)

list=list(map(int,input().split()))
max=0
s_max=0
for i in list:
  if (i>max):
    s_max=max
    max=i
  elif(s_max<i and i!=max):
    s_max=i
print(s_max)

list1=[1,4,3,6,7,0]
list2=sorted(list1)
print(list2)
print(list2[-2])

import math
n=int(input("entry"))

for i in range(1,n+1):
  members=int(input("enter members"))
  # print(members)
  price=int(input("enetr price"))
  # print(price)
  final_price=math.ceil(members/6)*price
  print(final_price)

x=int(input("enter started"))
assignment=3

# print(hour)
# print(assignment)
if(x<=22 and x<=22-assignment):
  print("able")
else:
  print("not able")

b1=int(input("b1:"))
b2=int(input("b2:"))
b3=int(input("b3:"))

b4=b1+b2+b3
if(b4>=2):
  print("not now")
else:
  print("time to fill")

x=int(input("enter amount"))
if x<=100:
  print(x)
elif 100<x<=1000:
  print(x-25)
elif 1000<x<=5000:
  print(x-100)
elif x>5000:
  print(x-500)

n=int(input("friends"))
x=int(input("piszza "))
t_piz=n*x
if t_piz%4==0:
  print(t_piz//4)
else:
  print((t_piz//4)+1)

n=int(input("n of glass:"))
amount=n*50
profit=amount-(70/100)*amount
print(profit)

string=input("")
last = string.split()
print(len(last[-1]))

string = input("")
count = 0
# Iterate through the string in reverse
for i in range(len(string) - 1, -1, -1):
    if string[i] == " ":
        break
    count += 1

print(count)

string = input("")
count = 0
# Iterate through the string in reverse
for i in range(len(string) - 1, -1, -1):
    if string[i] == " ":
        break
    count += 1

print(count)

list1=list(map(int,input().split()))
target_value=int(input())
count=0
pos=0

for i in range(len(list1)):
  if list1[i]==target_value:
    pos=list[1]
    count+=1
    break
if count==1:
  print(pos)
else:
      for i in range(len(list1)):
        if list1[i]>(target_value):
          print(i+1)
          break