# -*- coding: utf-8 -*-
"""day2 matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VjFt3GEgTpJNb5wgSgfdTeWPeOq0Ge2U
"""

import matplotlib.pyplot as plt
import pandas as pd

x=[1,2,3]
y=[4,5,2]


plt.plot(x,y)
plt.grid()
plt.show()

import pandas as pd


data={
    "salary":[25000,30000,37000,2800,39000,4800,55000]
}
df= pd.DataFrame(data)
print(df.head())
df.shape

plt.plot(df["salary"])
plt.grid()
plt.show()

plt.plot(df["salary"],color="skyblue",marker="o",linestyle=":",linewidth=5)
plt.grid()
plt.show()

plt.hist(df["salary"],bins=6,edgecolor="red")

plt.show()

df["dept"]=["HR","IT","FINANCE","HR","IT","FINANCE","HR"]
df.head()

count = df["dept"].value_counts()
count

plt.pie(count,labels=count.index,autopct="%1.6f",explode=[0,0,0,0])
plt.show()

df["age"]=[22,24,25,21,19,30,34]
df.head()

plt.bar(df["age"],df["salary"],color="skyblue",width=0.4)
plt.show()