# -*- coding: utf-8 -*-
"""day2 pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_T5ND059CoEUo22FEy3Jc4TnbvWmW9Dr
"""

pip install pandas

import pandas as pd
a= [1,False,"kanchu"]
myVar=pd.Series(a)
print(myVar)

print(myVar[0])

import pandas as pd
data ={
    "name":["anu","bhanu","chetu"],
    "age":[20,19,21],
    "city":["goa","surat","gadag"]
}
print(data)
print(pd.Series(data))

import pandas as pd
data ={
    "name":["anu","bhanu","chetu"],
    "age":[20,19,21],
    "city":["goa","surat","gadag"]
}
print(data)
print(pd.Series(data))
df=pd.DataFrame(data,index=[1,2,3])
print(df)

import pandas as pd

df=pd.read_csv("/content/customers-100.csv")
print(df)

import pandas as pd

df=pd.read_csv("/content/people_data.csv")
print(df)

import pandas as pd

df=pd.read_excel("/content/Weather_data.xlsx")
print(df)
print()

import pandas as pd

df=pd.read_csv("/content/people_data.csv",usecols=["First Name","Job Title"],nrows=3)
print(df)

import pandas as pd

df=pd.read_csv("/content/people_data.csv",usecols=["First Name","Job Title","Email"],skiprows=[4,5])
print(df)

import pandas as pd

# df=pd.read_csv("/content/people_data.csv",usecols=["First Name","Job Title"],nrows=3)
# print(df)
df.groupby(["First Name","Job Title"])
df

import pandas as pd

df=pd.read_csv("/content/people_data.csv")
# print(df)
f_df=df.loc[df["Sex"]=="Male",["First Name","Job Title"]]
print(f_df)

import pandas as pd

df=pd.read_csv("/content/people_data.csv")
# print(df)
f_df=df.loc[df["Job Title"]=="Games developer",["First Name","Job Title"]]
print(f_df)

df=pd.read_csv("/content/people_data.csv")
# print(df)
f_df=df.query("Sex=='Male' and `Job Title`=='Games developer'")
print(f_df)