# -*- coding: utf-8 -*-
"""day2 seaborn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKLHVngZ05OQBCGQzn4-bzGv5kFDof6Y
"""

import seaborn as sns
import matplotlib.pyplot as plt

df =sns.load_dataset("iris")

sns.pairplot(df)
plt.show()

sns.pairplot(df,hue="species")

import seaborn as sns
import matplotlib.pyplot as plt

df =sns.load_dataset("iris")

corr=df.corr(numeric_only=True)
sns.heatmap(corr,annot=True,cmap="YlGnBu")
plt.title("Correlation Heatmap")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

df =sns.load_dataset("iris")

sns.countplot(x="species",data=df)
plt.title("Count Plot")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

df =sns.load_dataset("iris")

sns.boxenplot(x="species",y="petal_length",data=df)
plt.title("box Plot")
plt.show()