# -*- coding: utf-8 -*-
"""day6 RFC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18lebIPN8BrcsSjD3DwZKU6GS0Ny-0J-G
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings("ignore")

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic_data = pd.read_csv(url)
print(titanic_data)

titanic_data = titanic_data.dropna(subset=["Survived"])
x = titanic_data[["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare"]]
y = titanic_data["Survived"]

x.loc[:, "Sex"] = x["Sex"].map({"female": 0, "male": 1})
x.loc[:, "Age"].fillna(x["Age"].median(), inplace=True)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(x_train, y_train)
y_pred = rf_classifier.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("\nClassification Report:\n", classification_rep)

sample = x_test.iloc[0:1]
prediction = rf_classifier.predict(sample)

sample_dict = sample.iloc[0].to_dict()
print(f"\nSample Passenger: {sample_dict}")
print(f"Predicted Survival: {'Survived' if prediction[0] == 1 else 'Did Not Survive'}")