# -*- coding: utf-8 -*-
"""day 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13HHVjO3XlJz_PLzg4s8Y1FC34i76X9Cw
"""

pip install numpy

import numpy as np
arr1=np.array([1,2,3,45])
print(arr1)

import numpy as np
arr1=np.array([[1,2,3,45],[5,6,6,78]])
arr2=np.array([5,6,6,78])
print(arr1)


for i in range(len(arr1)):
  for j in range(len(arr1[i])):
    print(arr1[i][j])

import numpy as np
arr1=np.array([[1,2,3,45],[5,6,6,78]])
arr2=np.array([5,6,6,78])
print(arr1)


for i in range(len(arr1)):
  for j in range(len(arr1[i])):
    print(i,j)

import numpy as np
arr1=np.array([[1,2,3,45],[5,6,6,78]])
print(arr1)
for i in range(len(arr1)):
  print(arr1[i] * arr1[i])

import numpy as np
arr1=np.array([[[1,2],[5,6]],[[21,6],[8,8]]])

print(arr1)
print(arr1[1][1][0])
print(type(arr1))
print(arr1.size)
print(arr1.dtype)
print(arr1.shape)

import numpy as np
print(np.zeros((3,3)))
print(np.eye((3)))
print(np.ones((3,3)))
print(np.linspace(1,5,10))
print(np.arange(0,10,2))

print(np.arange(0,10,2))

print(np.linspace(0,12,16))

import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.dot(a,b))

import numpy as np
a=np.random.rand(3,5)
print(a)
b=np.random.randint(1,100,(2,2))
print(b)